### ISSUE TITLE
iOS Error when connecting

### ISSUE THREAD

**Issue by vanlooverenkoen** [wonjerry/flutter_wifi_connector#8]
```
[] Failed to send a 9 message to nehelper: <dictionary: 0x2056d6390> { count = 1, transaction: 0, voucher = 0x0, contents =
	"XPCErrorDescription" => <string: 0x2056d6528> { length = 18, contents = "Connection invalid" }
}
[] NEHotspotConfigurationHelper failed to communicate to helper server.
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(connectToWifi, internal error., null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      WifiConnector.connectToWifi (package:wifi_connector/wifi_connector.dart:10:12)
<asynchronous suspension>
#3      _MyAppState._onConnectPressed (package:wifi_connector_example/main.dart:81:9)
<asynchronous suspension>

```

**Comment by vanlooverenkoen** [comment]
Anybody who was able to get this plugin working on iOS?
